# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713316fafc2d75e701ea5f8b1c43856462b8ae8240fef1d3575d21d202c124de63d7ef4c317d5836e58a6c751e4777141b6bdfa0e82199662c5f456e97a33dc3

test:
  secret_key_base: c3fb2440c249bad849fab2dc384691a642f80dea15d4e17c53fd8c383a7237cbd6d365e4266e065baf4aaa55c03205fe86dfb23cf82747c45dc7f4e1a63dffe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
